/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SejoursRouteImport } from './routes/sejours'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ReserverRouteImport } from './routes/reserver'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpotSpotIdRouteImport } from './routes/spot.$spotId'

const SejoursRoute = SejoursRouteImport.update({
  id: '/sejours',
  path: '/sejours',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverRoute = ReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotSpotIdRoute = SpotSpotIdRouteImport.update({
  id: '/spot/$spotId',
  path: '/spot/$spotId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/galerie': typeof GalerieRoute
  '/reception': typeof ReceptionRoute
  '/reserver': typeof ReserverRoute
  '/restaurant': typeof RestaurantRoute
  '/sejours': typeof SejoursRoute
  '/spot/$spotId': typeof SpotSpotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/galerie': typeof GalerieRoute
  '/reception': typeof ReceptionRoute
  '/reserver': typeof ReserverRoute
  '/restaurant': typeof RestaurantRoute
  '/sejours': typeof SejoursRoute
  '/spot/$spotId': typeof SpotSpotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/galerie': typeof GalerieRoute
  '/reception': typeof ReceptionRoute
  '/reserver': typeof ReserverRoute
  '/restaurant': typeof RestaurantRoute
  '/sejours': typeof SejoursRoute
  '/spot/$spotId': typeof SpotSpotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/evenements'
    | '/galerie'
    | '/reception'
    | '/reserver'
    | '/restaurant'
    | '/sejours'
    | '/spot/$spotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/evenements'
    | '/galerie'
    | '/reception'
    | '/reserver'
    | '/restaurant'
    | '/sejours'
    | '/spot/$spotId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/evenements'
    | '/galerie'
    | '/reception'
    | '/reserver'
    | '/restaurant'
    | '/sejours'
    | '/spot/$spotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  EvenementsRoute: typeof EvenementsRoute
  GalerieRoute: typeof GalerieRoute
  ReceptionRoute: typeof ReceptionRoute
  ReserverRoute: typeof ReserverRoute
  RestaurantRoute: typeof RestaurantRoute
  SejoursRoute: typeof SejoursRoute
  SpotSpotIdRoute: typeof SpotSpotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sejours': {
      id: '/sejours'
      path: '/sejours'
      fullPath: '/sejours'
      preLoaderRoute: typeof SejoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver': {
      id: '/reserver'
      path: '/reserver'
      fullPath: '/reserver'
      preLoaderRoute: typeof ReserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot/$spotId': {
      id: '/spot/$spotId'
      path: '/spot/$spotId'
      fullPath: '/spot/$spotId'
      preLoaderRoute: typeof SpotSpotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  EvenementsRoute: EvenementsRoute,
  GalerieRoute: GalerieRoute,
  ReceptionRoute: ReceptionRoute,
  ReserverRoute: ReserverRoute,
  RestaurantRoute: RestaurantRoute,
  SejoursRoute: SejoursRoute,
  SpotSpotIdRoute: SpotSpotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
